### PR TITLE
add ca-valencia and tiny update `add-from-corpuscrawler.sh`

### PR DESCRIPTION
**Pull request by hugolpz**
See commits. @brawer

### CODE REVIEW

**Comment by hugolpz** [comment]
CorpusCrawler has 1001 lists. So at least one is still missing from UNILEX.

**Comment by hugolpz** [comment]
@brawer , I think this pull request is pretty safe. Could you review it ?

**Comment by hugolpz** [comment]
@brawer, I plan delete my branch with the valencia data. Please accept or decline this PR before that.

**Comment by brawer** [comment]
Looks good, but can you sign the [Contributor License Agreement](https://cla-assistant.io/unicode-org/unilex?pullRequest=13)?

**Comment by hugolpz** [comment]
Done.

**Pull request merged**
